DROP DATABASE IF EXISTS WALMART_SALES_DATA;
CREATE DATABASE IF NOT EXISTS WALMART_SALES_DATA;

CREATE TABLE IF NOT EXISTS SALES(
	INVOICE_ID VARCHAR(30) NOT NULL PRIMARY KEY,
    BRANCH VARCHAR(5) NOT NULL,
    CITY VARCHAR(30) NOT NULL,
	CUSTOMER_TYPE VARCHAR(30) NOT NULL,
    GENDER VARCHAR(30) NOT NULL,
    PRODUCT_LINE VARCHAR(100) NOT NULL,
    UNIT_PRICE DECIMAL(10,2) NOT NULL,
    QUANTITY INT NOT NULL,
    VAT FLOAT(6,4) NOT NULL,
    TOTAL DECIMAL(12, 4) NOT NULL,
    DATE DATETIME NOT NULL,
    TIME_RANGE TIME NOT NULL,
    PAYMENT VARCHAR(15) NOT NULL,
    COGS DECIMAL(10,2) NOT NULL,
    GROSS_MARGIN_PCT FLOAT(11,9),
    GROSS_MARGIN DECIMAL(12, 4),
    RATING FLOAT(2, 1)
);

------------------------------------------------------------------------------------
-- TIME_OF_DAY

SELECT TIME_RANGE,
	(CASE 
		WHEN TIME_RANGE BETWEEN "00:00:00" AND "12:00:00" THEN "MORNING"
        WHEN TIME_RANGE BETWEEN "12:01:00" AND "16:00:00" THEN "AFTERNOON"
        ELSE "EVENING"
	END
    ) AS TIME_OF_DATE	
FROM SALES;

ALTER TABLE SALES ADD COLUMN TIME_OF_DAY VARCHAR(20);
UPDATE SALES 
SET TIME_OF_DAY = (
	CASE 
		WHEN TIME_RANGE BETWEEN "00:00:00" AND "12:00:00" THEN "MORNING"
        WHEN TIME_RANGE BETWEEN "12:01:00" AND "16:00:00" THEN "AFTERNOON"
        ELSE "EVENING"
	END
);

-- DAY_NAME

SELECT DATE FROM SALES;
SELECT DATE, dayname(DATE) FROM SALES;

ALTER TABLE SALES ADD COLUMN DAY_NAME VARCHAR(30);
UPDATE SALES
SET DAY_NAME = dayname(DATE);

-- MONTH_NAME

SELECT DATE, monthname(DATE) FROM SALES;
ALTER TABLE SALES ADD COLUMN MONTH_NAME VARCHAR (15);
UPDATE SALES SET MONTH_NAME = monthname(DATE);

-- HOW MANY UNIQUE CITIES DOES THE DATA HAVE ?
SELECT DISTINCT CITY FROM SALES;

-- IN WHICH CITY IS EACH BRANCH ?
SELECT DISTINCT CITY,BRANCH FROM SALES;

--------------------------------------------------------------------------------------

-- HOW MANY UNIQUE PRODUCT LINE DOES THE DATE HAVE ?
SELECT COUNT(DISTINCT PRODUCT_LINE) FROM SALES;

-- WHAT IS THE MOST COMMON PAYMENT METHOD IN DATA ?
SELECT PAYMENT, COUNT(PAYMENT) AS COUNT FROM SALES 
GROUP BY PAYMENT ORDER BY COUNT DESC;

-- WHAT IS THE 3 MOST SELLING PRODUCT LINE ?
SELECT PRODUCT_LINE, COUNT(QUANTITY) AS COUNT FROM SALES 
GROUP BY PRODUCT_LINE ORDER BY COUNT DESC LIMIT 3;

-- WHAT IS THE TOTAL REVENUE BY MONTH ?
SELECT MONTH_NAME AS MONTH, SUM(TOTAL) AS TOTAL_REVENUE FROM SALES 
GROUP BY MONTH_NAME ORDER BY TOTAL_REVENUE DESC ;

-- WHICH MONTH HAD THE LARGEST COGS ?
SELECT MONTH_NAME AS MONTH, SUM(COGS) AS TOTAL_COGS FROM SALES 
GROUP BY MONTH_NAME ORDER BY TOTAL_COGS DESC;

-- WHAT PRODUCT LINE HAD THE LARGEST REVENUE ?
SELECT PRODUCT_LINE, SUM(TOTAL) AS REVENUE FROM SALES GROUP BY PRODUCT_LINE ORDER BY REVENUE DESC;

-- WHAT IS THE CITY WITH LARGEST REVENUE ?





